### ISSUE TITLE
Automated build on Docker Hub does not work

### ISSUE THREAD

**Issue by michel-kraemer** [dergachev/screengif#30]
It seems the automated build on Docker Hub does not work anymore:
https://hub.docker.com/r/dergachev/screengif/builds/

The latest successful build was one year ago. Are you aware of this? Can it be fixed?

Thanks!

**Comment by dergachev** [comment]
Huh, good point:

Just looked at the output here: https://hub.docker.com/r/dergachev/screengif/builds/b53kwb8a28qkyngwo46cfje/

It seems that the issue is in this part of the Dockerfile:

```
RUN gem install bundler --no-rdoc --no-ri
ADD Gemfile /tmp/Gemfile
RUN cd /tmp; bundle install
```

Now we need to do something like this:

```
RUN gem install bundler --no-rdoc --no-ri
ADD Gemfile /tmp/Gemfile
ADD screengif.gemsepc /tmp/screengif.gemspec
RUN cd /tmp; bundle install
```

However this would need to be tested by someone before I'd merge it in, or I'll try and fix it eventually. :)

**Comment by michel-kraemer** [comment]
Yes. I tested it and it works. There is a typo though. Im going to send you a PR in a second.

Michel

**Comment by michel-kraemer** [comment]
OK. The PR is there. Thanks for solving this issue so quickly! 🍻 👍 

Michel
